name = "beta_types"
description = "Rudimentary types for embedded"
version = "0.1.0-dev"

authors = ["wolf biters"]
maintainers = ["wolf biters <the.wolf.biters@gmail.com>"]
maintainers-logins = ["wolfbiters"]
